= lab-insurance-eureka

image:https://travis-ci.org/labcabrera/lab-insurance-eureka.svg?branch=master["Build Status", link="https://travis-ci.org/labcabrera/lab-insurance-eureka"]

Servidor Eureka del proyecto https://github.com/labcabrera/lab-insurance[lab-insurance].

== Configuracion

La configuración de Eureka se resuelve a través de
https://cloud.spring.io/spring-cloud-config/[Spring Cloud Config] de modo que es necesario tener
levantado este servicio.

Para ello lo más sencillo será levantar en local la imagen del proyecto
https://github.com/labcabrera/lab-insurance-cloud-config-server[lab-insurance-cloud-config-server].

En el fichero _src/main/resources/bootstrap.yml_ podemos configurar los perfiles que deseemos.
También se ha incluído uno que obtiene la configuración de AWS, aunque generalmente no estará
levantado.

== Plugin de Docker

Para crear la imagen docker se utiliza el plugin https://github.com/palantir/gradle-docker[palantir]
de gradle.

Para crear la imagen simplemente ejecutaremos `gradle build docker`.

Y para ejecutar la imagen el comando run de docker:

----
$ docker run -i -p 8070:8070 -t labcabrera/lab-insurance-eureka
---- 

Una vez ejecutándose el contenedor podremos acceder a la consola de Eureka desde:

http://localhost:8070/

Despues para subir nuestra imagen simplemente crearemos el tag y haremos el push:

----
$ docker images
REPOSITORY                       TAG       IMAGE ID            CREATED             SIZE
labcabrera/lab-insurance-eureka  latest    03795944d6fc        5 minutes ago       128MB

...

$ docker tag 03795944d6fc labcabrera/lab-insurance-eureka:1.0.0

$ docker push labcabrera/lab-insurance-eureka:1.0.0
----

== Resources

* https://github.com/palantir/gradle-docker
* https://plugins.gradle.org/plugin/com.palantir.docker
* https://spring.io/guides/gs/spring-boot-docker/
